import { App, Notice, PluginSettingTab, Setting, TextComponent } from 'obsidian';
import NextLevelGtdPlugin from '../main';
import { t } from '../i18n';
import { NoteState } from '../NoteState';
import { setNoteState } from '../setNoteState';
import { ConfirmModal } from './ConfirmModal';
import { FolderSuggest } from './FolderSuggest';
import { VIEW_TYPE_INBOX } from './InboxView';
import type { InboxView } from './InboxView';
import { buildMockNotes, MOCK_FOLDER } from '../buildMockNotes';
